package com.example.yolanda.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.yolanda.data.Localizacion;

import com.example.yolanda.data.LocalizacionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localizacionDaoConfig;

    private final LocalizacionDao localizacionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localizacionDaoConfig = daoConfigMap.get(LocalizacionDao.class).clone();
        localizacionDaoConfig.initIdentityScope(type);

        localizacionDao = new LocalizacionDao(localizacionDaoConfig, this);

        registerDao(Localizacion.class, localizacionDao);
    }
    
    public void clear() {
        localizacionDaoConfig.getIdentityScope().clear();
    }

    public LocalizacionDao getLocalizacionDao() {
        return localizacionDao;
    }

}
