package com.example.yolanda.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOCALIZACION".
 */
public class Localizacion {

    private Long id;
    private String name;
    private Long limSouth;
    private Long limEast;
    private Long limNorth;
    private Long limWest;
    private Long lat;
    private Long lng;

    public Localizacion() {
    }

    public Localizacion(Long id) {
        this.id = id;
    }

    public Localizacion(Long id, String name, Long limSouth, Long limEast, Long limNorth, Long limWest, Long lat, Long lng) {
        this.id = id;
        this.name = name;
        this.limSouth = limSouth;
        this.limEast = limEast;
        this.limNorth = limNorth;
        this.limWest = limWest;
        this.lat = lat;
        this.lng = lng;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getLimSouth() {
        return limSouth;
    }

    public void setLimSouth(Long limSouth) {
        this.limSouth = limSouth;
    }

    public Long getLimEast() {
        return limEast;
    }

    public void setLimEast(Long limEast) {
        this.limEast = limEast;
    }

    public Long getLimNorth() {
        return limNorth;
    }

    public void setLimNorth(Long limNorth) {
        this.limNorth = limNorth;
    }

    public Long getLimWest() {
        return limWest;
    }

    public void setLimWest(Long limWest) {
        this.limWest = limWest;
    }

    public Long getLat() {
        return lat;
    }

    public void setLat(Long lat) {
        this.lat = lat;
    }

    public Long getLng() {
        return lng;
    }

    public void setLng(Long lng) {
        this.lng = lng;
    }

}
